[package]
name = "rusty_dragon"
version = "1.0.0"
edition = "2018"

[dependencies]
nom = "6"
zstd = "0.9"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
strum = "0.22.0"
strum_macros = "0.22"
num-traits = "0.2"
num-derive = "0.3"